### ISSUE TITLE
Sequelize typing causes errors

### ISSUE THREAD

**Issue by SelflessPotato** [SelflessPotato/Typically_Bot#14]
Typescripting in Sequelize isn't defined properly, resulting in errors:

```
[2022-01-01T00:16:05.913Z] ERROR: 
 SequelizeUniqueConstraintError  Validation error
    at Database.<anonymous> (sequelize)
    at C:\Users\SelflessPotato\Documents\Typically_Bot\node_modules\sequelize\lib\dialects\sqlite\query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (sequelize)
    at C:\Users\SelflessPotato\Documents\Typically_Bot\node_modules\sequelize\lib\sequelize.js:642:28
    at SQLiteQueryInterface.update (sequelize)
    at User.save (sequelize)
```

**Comment by paperclover** [comment]
will be closed by #15
